### ISSUE TITLE
Using wait-on with circle-ci

### ISSUE THREAD

**Issue by arichter83** [jeffbski/wait-on#40]
I was using wait-on on CircleCI like this to run cypress tests but it did't work:

```
      - run: npm start & ./node_modules/.bin/wait-on http://localhost:3000
      - run: ./node_modules/.bin/cypress run --config video=false
```

I got the message:

```
Cypress could not verify that the server set as your `baseUrl` is running:
  > http://localhost:3000
```

This was most likely because CircleCI killed the background process to quickly. A solution is using `background: true`:

```
      - run:
          command: npm start
          background: true
      - run: ./node_modules/.bin/wait-on http://localhost:3000
      - run: ./node_modules/.bin/cypress run --config video=false
```
